name: Notify on Issue
on:
    issues:
        types: [opened, edited, milestoned]

jobs:
    slack-message:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: echo "test"
